advancements_dataversion_min = 2724
advancements_dataversion_piglin_brute_addition = 2578
# dataversion 1.16.1 = 2567
# dataversion 1.16.2 = 2578
# dataversion 1.16.4 = 2584
advancements_dataversion_max = 1000000

# The key values are the names within the advancement json file.
# The commented lines are advancements that have separate progress sheet to control it.
links = {
    "advancements_minecraft": {
        "minecraft:story/root": "Advancements!A8",
        "minecraft:story/mine_stone": "Advancements!A9",
        "minecraft:story/upgrade_tools": "Advancements!A10",
        "minecraft:story/smelt_iron": "Advancements!A11",
        "minecraft:story/obtain_armor": "Advancements!A12",
        "minecraft:story/lava_bucket": "Advancements!A13",
        "minecraft:story/iron_tools": "Advancements!A14",
        "minecraft:story/deflect_arrow": "Advancements!A15",
        "minecraft:story/form_obsidian": "Advancements!A16",
        "minecraft:story/mine_diamond": "Advancements!A17",
        "minecraft:story/enter_the_nether": "Advancements!A18",
        "minecraft:story/shiny_gear": "Advancements!A19",
        "minecraft:story/enchant_item": "Advancements!A20",
        "minecraft:story/cure_zombie_villager": "Advancements!A21",
        "minecraft:story/follow_ender_eye": "Advancements!A22",
        "minecraft:story/enter_the_end": "Advancements!A23",
    },

    "advancements_husbandry": {
        "minecraft:husbandry/root": "Advancements!A27",
        "minecraft:husbandry/safely_harvest_honey": "Advancements!A28",
        "minecraft:husbandry/breed_an_animal": "Advancements!A29",
        "minecraft:husbandry/ride_a_boat_with_a_goat": "Advancements!A30",
        "minecraft:husbandry/tame_an_animal": "Advancements!A31",
        "minecraft:husbandry/make_a_sign_glow": "Advancements!A32",
        "minecraft:husbandry/fishy_business": "Advancements!A33",
        "minecraft:husbandry/silk_touch_nest": "Advancements!A34",
        "minecraft:husbandry/plant_seed": "Advancements!A35",
        "minecraft:husbandry/wax_on": "Advancements!A36",
        #"minecraft:husbandry/bred_all_animals": "Advancements!A37",
        #"minecraft:husbandry/complete_catalogue": "Advancements!A38",
        "minecraft:husbandry/tactical_fishing": "Advancements!A39",
        #"minecraft:husbandry/balanced_diet": "Advancements!A40",
        "minecraft:husbandry/obtain_netherite_hoe": "Advancements!A41",
        "minecraft:husbandry/wax_off": "Advancements!A42",
        "minecraft:husbandry/axolotl_in_a_bucket": "Advancements!A43",
        "minecraft:husbandry/kill_axolotl_target": "Advancements!A44",
    },

    "advancements_adventure": {
        "minecraft:adventure/root": "Advancements!A48",
        "minecraft:adventure/voluntary_exile": "Advancements!A49",
        "minecraft:adventure/spyglass_at_parrot": "Advancements!A50",
        "minecraft:adventure/kill_a_mob": "Advancements!A51",
        "minecraft:adventure/trade": "Advancements!A52",
        "minecraft:adventure/honey_block_slide": "Advancements!A53",
        "minecraft:adventure/ol_betsy": "Advancements!A54",
        "minecraft:adventure/lightning_rod_with_villager_no_fire": "Advancements!A55",
        "minecraft:adventure/walk_on_powder_snow_with_leather_boots": "Advancements!A56",
        "minecraft:adventure/sleep_in_bed": "Advancements!A57",
        "minecraft:adventure/hero_of_the_village": "Advancements!A58",
        "minecraft:adventure/spyglass_at_ghast": "Advancements!A59",
        "minecraft:adventure/throw_trident": "Advancements!A60",
        "minecraft:adventure/shoot_arrow": "Advancements!A61",
        #"minecraft:adventure/kill_all_mobs": "Advancements!A62",
        "minecraft:adventure/totem_of_undying": "Advancements!A63",
        "minecraft:adventure/summon_iron_golem": "Advancements!A64",
        "minecraft:adventure/two_birds_one_arrow": "Advancements!A65",
        "minecraft:adventure/whos_the_pillager_now": "Advancements!A66",
        "minecraft:adventure/arbalistic": "Advancements!A67",
        #"minecraft:adventure/adventuring_time": "Advancements!A68",
        "minecraft:adventure/spyglass_at_dragon": "Advancements!A69",
        "minecraft:adventure/very_very_frightening": "Advancements!A70",
        "minecraft:adventure/sniper_duel": "Advancements!A71",
        "minecraft:adventure/bullseye": "Advancements!A72",
    },

    "advancements_nether": {
        "minecraft:nether/root": "Advancements!A76",
        "minecraft:nether/return_to_sender": "Advancements!A77",
        "minecraft:nether/find_bastion": "Advancements!A78",
        "minecraft:nether/obtain_ancient_debris": "Advancements!A79",
        "minecraft:nether/fast_travel": "Advancements!A80",
        "minecraft:nether/find_fortress": "Advancements!A81",
        "minecraft:nether/obtain_crying_obsidian": "Advancements!A82",
        "minecraft:nether/distract_piglin": "Advancements!A83",
        "minecraft:nether/ride_strider": "Advancements!A84",
        "minecraft:nether/uneasy_alliance": "Advancements!A85",
        "minecraft:nether/loot_bastion": "Advancements!A86",
        "minecraft:nether/use_lodestone": "Advancements!A87",
        "minecraft:nether/netherite_armor": "Advancements!A88",
        "minecraft:nether/get_wither_skull": "Advancements!A89",
        "minecraft:nether/obtain_blaze_rod": "Advancements!A90",
        "minecraft:nether/charge_respawn_anchor": "Advancements!A91",
        #"minecraft:nether/explore_nether": "Advancements!A92",
        "minecraft:nether/summon_wither": "Advancements!A93",
        "minecraft:nether/brew_potion": "Advancements!A94",
        "minecraft:nether/create_beacon": "Advancements!A95",
        "minecraft:nether/all_potions": "Advancements!A96",
        "minecraft:nether/create_full_beacon": "Advancements!A97",
        "minecraft:nether/all_effects": "Advancements!A98",
    },

    "advancements_end": {
        "minecraft:end/root": "Advancements!A102",
        "minecraft:end/kill_dragon": "Advancements!A103",
        "minecraft:end/dragon_egg": "Advancements!A104",
        "minecraft:end/enter_end_gateway": "Advancements!A105",
        "minecraft:end/respawn_dragon": "Advancements!A106",
        "minecraft:end/dragon_breath": "Advancements!A107",
        "minecraft:end/find_end_city": "Advancements!A108",
        "minecraft:end/elytra": "Advancements!A109",
        "minecraft:end/levitate": "Advancements!A110",
    },

    # progress_breeding
    "minecraft:husbandry/bred_all_animals": {
        "minecraft:axolotl": "MobsBred!A5",
        "minecraft:bee": "MobsBred!A6",
        "minecraft:cat": "MobsBred!A7",
        "minecraft:chicken": "MobsBred!A8",
        "minecraft:cow": "MobsBred!A9",
        "minecraft:donkey": "MobsBred!A10",
        "minecraft:fox": "MobsBred!A11",
        "minecraft:goat": "MobsBred!A12",
        "minecraft:hoglin": "MobsBred!A13",
        "minecraft:horse": "MobsBred!A14",
        "minecraft:llama": "MobsBred!A15",
        "minecraft:mooshroom": "MobsBred!A16",
        "minecraft:mule": "MobsBred!A17",
        "minecraft:ocelot": "MobsBred!A18",
        "minecraft:panda": "MobsBred!A19",
        "minecraft:pig": "MobsBred!A20",
        "minecraft:rabbit": "MobsBred!A21",
        "minecraft:sheep": "MobsBred!A22",
        "minecraft:strider": "MobsBred!A23",
        "minecraft:turtle": "MobsBred!A24",
        "minecraft:wolf": "MobsBred!A25",
    },

    # progress_cats_catalogue
    "minecraft:husbandry/complete_catalogue": {
        "textures/entity/cat/tabby.png": "TamedCats!A5",
        "textures/entity/cat/black.png": "TamedCats!A6",
        "textures/entity/cat/red.png": "TamedCats!A7",
        "textures/entity/cat/siamese.png": "TamedCats!A8",
        "textures/entity/cat/british_shorthair.png": "TamedCats!A9",
        "textures/entity/cat/calico.png": "TamedCats!A10",
        "textures/entity/cat/persian.png": "TamedCats!A11",
        "textures/entity/cat/ragdoll.png": "TamedCats!A12",
        "textures/entity/cat/white.png": "TamedCats!A13",
        "textures/entity/cat/jellie.png": "TamedCats!A14",
        "textures/entity/cat/all_black.png": "TamedCats!A15",
    },

    # progress_balanced_diet
    "minecraft:husbandry/balanced_diet": {
        "apple": "BalancedDiet!A5",
        "baked_potato": "BalancedDiet!A6",
        "beetroot": "BalancedDiet!A7",
        "beetroot_soup": "BalancedDiet!A8",
        "bread": "BalancedDiet!A9",
        "carrot": "BalancedDiet!A10",
        "chorus_fruit": "BalancedDiet!A11",
        "cooked_chicken": "BalancedDiet!A12",
        "cooked_cod": "BalancedDiet!A13",
        "cooked_mutton": "BalancedDiet!A14",
        "cooked_porkchop": "BalancedDiet!A15",
        "cooked_rabbit": "BalancedDiet!A16",
        "cooked_salmon": "BalancedDiet!A17",
        "cookie": "BalancedDiet!A18",
        "dried_kelp": "BalancedDiet!A19",
        "enchanted_golden_apple": "BalancedDiet!A20",
        "glow_berries": "BalancedDiet!A21",
        "golden_apple": "BalancedDiet!A22",
        "golden_carrot": "BalancedDiet!A23",
        "honey_bottle": "BalancedDiet!A24",
        "melon_slice": "BalancedDiet!A25",
        "mushroom_stew": "BalancedDiet!A26",
        "poisonous_potato": "BalancedDiet!A27",
        "potato": "BalancedDiet!A28",
        "pufferfish": "BalancedDiet!A29",
        "pumpkin_pie": "BalancedDiet!A30",
        "rabbit_stew": "BalancedDiet!A31",
        "beef": "BalancedDiet!A32",
        "chicken": "BalancedDiet!A33",
        "cod": "BalancedDiet!A34",
        "mutton": "BalancedDiet!A35",
        "porkchop": "BalancedDiet!A36",
        "rabbit": "BalancedDiet!A37",
        "salmon": "BalancedDiet!A38",
        "rotten_flesh": "BalancedDiet!A39",
        "spider_eye": "BalancedDiet!A40",
        "cooked_beef": "BalancedDiet!A41",
        "suspicious_stew": "BalancedDiet!A42",
        "sweet_berries": "BalancedDiet!A43",
        "tropical_fish": "BalancedDiet!A44",
    },

    # progress_monsters_hunted
    "minecraft:adventure/kill_all_mobs": {
        "minecraft:blaze": "MonstersHunted!A5",
        "minecraft:cave_spider": "MonstersHunted!A6",
        "minecraft:creeper": "MonstersHunted!A7",
        "minecraft:drowned": "MonstersHunted!A8",
        "minecraft:elder_guardian": "MonstersHunted!A9",
        "minecraft:ender_dragon": "MonstersHunted!A10",
        "minecraft:enderman": "MonstersHunted!A11",
        "minecraft:endermite": "MonstersHunted!A12",
        "minecraft:evoker": "MonstersHunted!A13",
        "minecraft:ghast": "MonstersHunted!A14",
        "minecraft:guardian": "MonstersHunted!A15",
        "minecraft:hoglin": "MonstersHunted!A16",
        "minecraft:husk": "MonstersHunted!A17",
        "minecraft:magma_cube": "MonstersHunted!A18",
        "minecraft:phantom": "MonstersHunted!A19",
        "minecraft:piglin": "MonstersHunted!A20",
        "minecraft:piglin_brute": "MonstersHunted!A21",
        "minecraft:pillager": "MonstersHunted!A22",
        "minecraft:ravager": "MonstersHunted!A23",
        "minecraft:shulker": "MonstersHunted!A24",
        "minecraft:silverfish": "MonstersHunted!A25",
        "minecraft:skeleton": "MonstersHunted!A26",
        "minecraft:slime": "MonstersHunted!A27",
        "minecraft:spider": "MonstersHunted!A28",
        "minecraft:stray": "MonstersHunted!A29",
        "minecraft:vex": "MonstersHunted!A30",
        "minecraft:vindicator": "MonstersHunted!A31",
        "minecraft:witch": "MonstersHunted!A32",
        "minecraft:wither": "MonstersHunted!A33",
        "minecraft:wither_skeleton": "MonstersHunted!A34",
        "minecraft:zoglin": "MonstersHunted!A35",
        "minecraft:zombie": "MonstersHunted!A36",
        "minecraft:zombie_villager": "MonstersHunted!A37",
        "minecraft:zombified_piglin": "MonstersHunted!A38",
    },

    # progress_biomes_visited
    "minecraft:adventure/adventuring_time": {
        "minecraft:badlands": "Biomes!A5",
        "minecraft:badlands_plateau": "Biomes!A6",
        "minecraft:bamboo_jungle": "Biomes!A7",
        "minecraft:bamboo_jungle_hills": "Biomes!A8",
        "minecraft:beach": "Biomes!A9",
        "minecraft:birch_forest": "Biomes!A10",
        "minecraft:birch_forest_hills": "Biomes!A11",
        "minecraft:cold_ocean": "Biomes!A12",
        "minecraft:dark_forest": "Biomes!A13",
        "minecraft:deep_cold_ocean": "Biomes!A14",
        "minecraft:deep_frozen_ocean": "Biomes!A15",
        "minecraft:deep_lukewarm_ocean": "Biomes!A16",
        "minecraft:desert": "Biomes!A17",
        "minecraft:desert_hills": "Biomes!A18",
        "minecraft:forest": "Biomes!A19",
        "minecraft:frozen_river": "Biomes!A20",
        "minecraft:giant_tree_taiga": "Biomes!A21",
        "minecraft:giant_tree_taiga_hills": "Biomes!A22",
        "minecraft:jungle": "Biomes!A23",
        "minecraft:jungle_edge": "Biomes!A24",
        "minecraft:jungle_hills": "Biomes!A25",
        "minecraft:lukewarm_ocean": "Biomes!A26",
        "minecraft:mountains": "Biomes!A27",
        "minecraft:mushroom_field_shore": "Biomes!A28",
        "minecraft:mushroom_fields": "Biomes!A29",
        "minecraft:plains": "Biomes!A30",
        "minecraft:river": "Biomes!A31",
        "minecraft:savanna": "Biomes!A32",
        "minecraft:savanna_plateau": "Biomes!A33",
        "minecraft:snowy_beach": "Biomes!A34",
        "minecraft:snowy_mountains": "Biomes!A35",
        "minecraft:snowy_taiga": "Biomes!A36",
        "minecraft:snowy_taiga_hills": "Biomes!A37",
        "minecraft:snowy_tundra": "Biomes!A38",
        "minecraft:stone_shore": "Biomes!A39",
        "minecraft:swamp": "Biomes!A40",
        "minecraft:taiga": "Biomes!A41",
        "minecraft:taiga_hills": "Biomes!A42",
        "minecraft:warm_ocean": "Biomes!A43",
        "minecraft:wooded_badlands_plateau": "Biomes!A44",
        "minecraft:wooded_hills": "Biomes!A45",
        "minecraft:wooded_mountains": "Biomes!A46",
    },

    # progress_nether_biomes_visited
    "minecraft:nether/explore_nether": {
        "minecraft:basalt_deltas": "NetherBiomes!A5",
        "minecraft:crimson_forest": "NetherBiomes!A6",
        "minecraft:nether_wastes": "NetherBiomes!A7",
        "minecraft:soul_sand_valley": "NetherBiomes!A8",
        "minecraft:warped_forest": "NetherBiomes!A9",
    },
}